### ISSUE TITLE
[BUG]ビンゴ番号を引く処理が2回実行される

### ISSUE THREAD

**Issue by Kawatan1927** [Kawatan1927/bingo-game-2024#1]
## バグの説明

- 抽選するボタンを1回クリックすると、2つの番号が連続で抽選される

**Comment by hikaruYahagi** [comment]
script.jsの51〜65行目の処理の削除忘れによるものだと思われます。
確認よろしくお願いします。

**Comment by Kawatan1927** [comment]
> script.jsの51〜65行目の処理の削除忘れによるものだと思われます。 確認よろしくお願いします。

ありがとうございます！修正します
